const mongoose = require('mongoose'); //will help us interface with MongoDB
mongoose.Promise = global.Promise; //Assigns the mongoose promise the native code in the global object promise
const slug = require('slugs'); //Can make url friendly names for our slugs

const storeSchema = new mongoose.Schema({  //this is the model
	name: {
		type: String,
		trim: true, 
		required: 'Please enter a store name!'
	},
	slug: String, //will be autogenerated whenever someone saves, other schema will be provided by us
	description: {
		type: String, 
		trim: true
	},
	tags: [String]
});


storeSchema.pre('save', function(next) { //this funciton only needs to run when the name has been changed
	if(!this.isModified('name')){
		next() //skip it
		return;
	}
	this.slug = slug(this.name); //this is equal to the Store we are trying to save
	next(); // will come back and make more advance - if 2 store names are the same for this, it will overlap the slugs. This is bad. 
})

module.exports = mongoose.model('Store', storeSchema);